/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*!
 * \file cpp/model.cpp
 * \brief Implementation of C++14 Model API for TVM DSP Runtime
 */

#include "model.h"  /* Public API header from include/ */

#include <cstring>

/* Platform headers - may include C++ on host */
#include "../platform/dsp_platform.h"
#include "../platform/cycle_counter.h"

/* C API headers */
extern "C" {
#include "../ffi/ffi_types.h"
#include "../container/ndarray.h"
#include "../container/array.h"
#include "../constants/constants.h"
#include "../vm/vm_builtins.h"
}

/* constants_loader.h has its own extern "C" guards and may include C++ headers */
#include "../constants/constants_loader.h"

/*
 * Forward declaration for generated DSP wrapper function.
 * This is generated by codegen_c_static.cc for DSP targets.
 */
extern "C" int cg_main_dsp(TVMFFIAny* inputs, int num_inputs,
                           TVMFFIAny* constants, TVMFFIAny* output);

namespace tvm {
namespace dsp {

// ============================================================
// Model Implementation
// ============================================================

Model::Model()
    : constants_(nullptr),
      const_count_(0),
      last_cycles_(0),
      initialized_(false),
      platform_initialized_(false),
      output_count_(0) {
  std::memset(output_views_, 0, sizeof(output_views_));
}

Model::~Model() {
  Cleanup();
}

Model::Model(Model&& other) noexcept
    : constants_(other.constants_),
      const_count_(other.const_count_),
      last_cycles_(other.last_cycles_),
      initialized_(other.initialized_),
      platform_initialized_(other.platform_initialized_),
      output_count_(other.output_count_) {
  /* Copy output views */
  std::memcpy(output_views_, other.output_views_, sizeof(output_views_));

  /* Clear other to prevent double cleanup */
  other.constants_ = nullptr;
  other.const_count_ = 0;
  other.last_cycles_ = 0;
  other.initialized_ = false;
  other.platform_initialized_ = false;
  other.output_count_ = 0;
  std::memset(other.output_views_, 0, sizeof(other.output_views_));
}

Model& Model::operator=(Model&& other) noexcept {
  if (this != &other) {
    /* Clean up current state */
    Cleanup();

    /* Move from other */
    constants_ = other.constants_;
    const_count_ = other.const_count_;
    last_cycles_ = other.last_cycles_;
    initialized_ = other.initialized_;
    platform_initialized_ = other.platform_initialized_;
    output_count_ = other.output_count_;
    std::memcpy(output_views_, other.output_views_, sizeof(output_views_));

    /* Clear other */
    other.constants_ = nullptr;
    other.const_count_ = 0;
    other.last_cycles_ = 0;
    other.initialized_ = false;
    other.platform_initialized_ = false;
    other.output_count_ = 0;
    std::memset(other.output_views_, 0, sizeof(other.output_views_));
  }
  return *this;
}

void Model::Cleanup() {
  if (initialized_) {
    /* Clean up register file (frees intermediate objects) */
    TVMDSPRegFileCleanup();

    /* Clean up constants */
    TVMDSPConstantsCleanup();

    initialized_ = false;
  }

  if (platform_initialized_) {
    tvm_dsp_platform_shutdown();
    platform_initialized_ = false;
  }

  constants_ = nullptr;
  const_count_ = 0;
}

ModelError Model::Load(const void* weights_data, size_t weights_size) {
  /* Clean up any previous state */
  Cleanup();

  /* Step 1: Initialize platform */
  if (tvm_dsp_platform_init() != 0) {
    return ModelError::kPlatformInitFailed;
  }
  platform_initialized_ = true;

  /* Step 2: Parse constants */
  int parse_result;

  if (weights_data != nullptr && weights_size > 0) {
    /* Use provided weights data */
    TVMDSPConstantsInit();
    parse_result = TVMDSPConstantsParse(weights_data, weights_size);
  } else {
    /* Use configured source (embedded or filesystem) */
    parse_result = TVMDSPParseConstants();
  }

  if (parse_result < 0) {
    Cleanup();
    return ModelError::kConstantsParseFailed;
  }

  /* Step 3: Get constants array */
  const_count_ = 0;
  constants_ = TVMDSPConstantsGet(&const_count_);

  if (constants_ == nullptr || const_count_ == 0) {
    Cleanup();
    return ModelError::kConstantsParseFailed;
  }

  initialized_ = true;
  return ModelError::kSuccess;
}

ModelError Model::InferInternal(NDArray* input, TVMFFIAny* output_any) {
  if (!initialized_) {
    return ModelError::kNotLoaded;
  }

  if (input == nullptr || output_any == nullptr) {
    return ModelError::kNullInput;
  }

  /* Create temporary TVMDSPNDArray wrapper for input */
  DLDevice device = {kDLCPU, 0};
  TVMDSPNDArray* input_arr = TVMDSPNDArrayFromData(
      input->data,
      input->shape,
      input->ndim,
      input->dtype,
      device);

  if (input_arr == nullptr) {
    return ModelError::kNullInput;
  }

  /* Prepare input as TVMFFIAny */
  TVMFFIAny input_any;
  input_any.type_index = kTVMFFITensor;
  input_any.small_len = 0;
  input_any.v_obj = reinterpret_cast<TVMFFIObject*>(input_arr);
  input_arr->ref_counter++;

  /* Clear output */
  std::memset(output_any, 0, sizeof(*output_any));

  /* Measure inference time */
  TVMDSPCycleCounter_init();
  uint64_t cycles_start = TVMDSPCycleCounter_getCount64();

  /* Call generated wrapper */
  int ret = cg_main_dsp(&input_any, 1, constants_, output_any);

  uint64_t cycles_end = TVMDSPCycleCounter_getCount64();
  last_cycles_ = TVMDSPCycleCounter_elapsed(cycles_start, cycles_end);

  if (ret != 0) {
    return ModelError::kInferenceFailed;
  }

  return ModelError::kSuccess;
}

ModelError Model::Infer(NDArray* input, NDArray** output) {
  if (output == nullptr) {
    return ModelError::kNullInput;
  }

  /* Run inference */
  TVMFFIAny output_any;
  ModelError err = InferInternal(input, &output_any);
  if (err != ModelError::kSuccess) {
    return err;
  }

  /* Handle output based on type */
  if (output_any.type_index == kTVMFFITensor) {
    /* Single output - direct NDArray */
    output_count_ = 1;
    TVMDSPNDArray* out_arr = reinterpret_cast<TVMDSPNDArray*>(output_any.v_obj);

    output_views_[0].data = out_arr->data;
    output_views_[0].shape = out_arr->shape;
    output_views_[0].ndim = out_arr->ndim;
    output_views_[0].dtype = out_arr->dtype;
    output_views_[0].ref_counter = out_arr->ref_counter;

    *output = &output_views_[0];

  } else if (output_any.type_index == kTVMFFIArray) {
    /* Multi-output - array of NDArrays */
    TVMDSPArray* arr = reinterpret_cast<TVMDSPArray*>(output_any.v_obj);
    output_count_ = arr->size;

    /* Populate all output views */
    for (int i = 0; i < arr->size && i < kMaxOutputs; i++) {
      TVMFFIAny* elem = &arr->elements[i];
      if (elem->type_index == kTVMFFITensor && elem->v_obj != nullptr) {
        TVMDSPNDArray* out_arr = reinterpret_cast<TVMDSPNDArray*>(elem->v_obj);
        output_views_[i].data = out_arr->data;
        output_views_[i].shape = out_arr->shape;
        output_views_[i].ndim = out_arr->ndim;
        output_views_[i].dtype = out_arr->dtype;
        output_views_[i].ref_counter = out_arr->ref_counter;
      }
    }

    /* Return first output for backward compatibility */
    if (output_count_ > 0) {
      *output = &output_views_[0];
    } else {
      return ModelError::kInvalidOutputType;
    }

  } else {
    return ModelError::kInvalidOutputType;
  }

  return ModelError::kSuccess;
}

ModelError Model::InferMulti(NDArray* input, NDArray** outputs, int* num_outputs) {
  if (outputs == nullptr || num_outputs == nullptr) {
    return ModelError::kNullInput;
  }

  /* Run inference with single-output API (it populates output_views_) */
  NDArray* first_output;
  ModelError err = Infer(input, &first_output);
  if (err != ModelError::kSuccess) {
    return err;
  }

  /* Return all outputs */
  *num_outputs = output_count_;
  for (int i = 0; i < output_count_; i++) {
    outputs[i] = &output_views_[i];
  }

  return ModelError::kSuccess;
}

MemoryStats Model::GetMemoryStats(MemoryPool pool) const {
  MemoryStats stats = {0, 0, 0, 0, 0};

  TVMDSPMemoryPool c_pool = (pool == MemoryPool::kFast)
                                ? TVM_DSP_MEM_FAST
                                : TVM_DSP_MEM_MAIN;

  TVMDSPMemoryStats c_stats;
  tvm_dsp_get_memory_stats(c_pool, &c_stats);

  stats.total_size = c_stats.total_size;
  stats.used_size = c_stats.used_size;
  stats.peak_used = c_stats.peak_used;
  stats.alloc_count = c_stats.alloc_count;
  stats.free_count = c_stats.free_count;

  return stats;
}

}  // namespace dsp
}  // namespace tvm
