/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*!
 * \file tvm_dsp_dma_host.c
 * \brief TVM DSP DMA - Host emulation implementation
 *
 * Provides memcpy-based DMA for host emulation builds (host, c7x_host).
 * The async DMA + double-buffering generated by InjectSoftwarePipeline
 * runs correctly -- just without overlapping DMA and compute.
 */

#include "tvm_dsp_dma.h"

#include <string.h>

int tvm_dsp_dma_init(int num_channels) {
  (void)num_channels;
  return 0;
}

void tvm_dsp_dma_deinit(void) {
}

int tvm_dsp_dma_copy(int queue_id, void* dst, const void* src,
                     int size, int bypass_cache) {
  (void)queue_id;
  (void)bypass_cache;
  memcpy(dst, src, (size_t)size);
  return 0;
}

int tvm_dsp_dma_wait(int queue_id, int max_inflight) {
  (void)queue_id;
  (void)max_inflight;
  return 0;
}
